POST http://localhost:3111/api/visits
Content-Type: application/json
Authorization: bearer VybmFtZSI6ImVsaXNhIiwiaWQiOiI2MmU2YTJiMjRkN2YzNjU3Nzg4MDhiNTYiLCJpYXQiOjE2NjA4MjY1MzV9.jGGCOQ3s2DaEztdbV0mRx4XAV33KTBdy-2coz6UB9Vg

{
    "what": "test visit token 3",
    "where": "test place 2",
    "category": ["test", "fancy post test"],
    "how": ["train", "car"],
    "timeLength": "month",
    "timeOfYear": ["winter", "summer"],
    "priceCategory": "$$",
    "easeOfOrganization": "easy",
    "notes": "yada yada yada"
}