POST http://localhost:3111/api/visits
Content-Type: application/json

{
    "what": "test visit 2",
    "where": "test place 2",
    "category": ["test", "fancy post test"],
    "how": ["train", "car"],
    "timeLength": "month",
    "timeOfYear": ["winter", "summer"],
    "priceCategory": "$$",
    "easeOfOrganization": "easy",
    "notes": "yada yada yada"
}